// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://drmeirstjaldsnbxhney.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRybWVpcnN0amFsZHNuYnhobmV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0MTc0NTIsImV4cCI6MjA3Mzk5MzQ1Mn0.HGJFL2BOMisGfOT4VdpErlAHXnaHy8SuxJN9Q4JXWlg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});